apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard  # Ganti dengan nomor port sebenarnya jika "dashboard" bukan target port yang valid
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: web  # Ganti dengan nomor port sebenarnya jika "web" bukan target port yang valid
  selector:
    app: traefik
