apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-account.yaml
- 02-role.yaml
- 03-role-binding.yaml
- 04-traefik-services.yaml
- 05-traefik.yaml
- metallb/metal.yaml
- service/ingress.yaml
- service/app1/nodejs-deploymen.yaml
- service/app2/nodejs2-deploymen.yaml
