apiVersion: v1
kind: Namespace
metadata:
  name: app1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: teknikhub/nodejs:latest
          ports:
            - containerPort: 3000
      nodeSelector:
        node-role.kubernetes.io/node1: "" 
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: default
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
